### ISSUE TITLE
iOS wallet request

### ISSUE THREAD

**Issue by chikiuso** [primecoin/primecoin#103]
May I ask would there be an iOS wallet or full node implementation for primecoin? I would like to put my primecoin on iPad if possible, thanks for your help

**Comment by turnkit** [comment]
this is probably done easiest if Primecoin could get included with Coinomi

apparently they were interested in the past but it didn't go through for some reason: "Unfortunately previous talks did not come to anything. We may reconnect in the future." - Apr 2, 2019, @CoinomiWallet

https://twitter.com/coinomisupport/status/1010427390848262145?lang=en

**Comment by chikiuso** [comment]
Thanks @turnkit  , let me try to persuade them
