### ISSUE TITLE
MacOS Build

### ISSUE THREAD

**Issue by turnkit** [primecoin/primecoin#38]
Can I help get a MacOS port built somehow?

**Comment by turnkit** [comment]
thx Sunny and eXtremal for your updates.

I see eXtremal had done a Mac OS port in the past here: https://bitcointalk.org/index.php?topic=4454417 

So am hopeful.

I am running 10.14.5 and I think I have a 10.13 system also and another old system (10.7?) if you need binaries compiled. I can type 'make' and edit files but beyond that don't have much skill.  But glad to compile and upload binaries if wanted.

**Comment by eXtremal-ik7** [comment]
Stable MacOS X release not present.
Latest unstable beta can be obtained here: http://coinsforall.io/distr/primecoin-core/primecoin-0.1.5-rc1-osx.dmg
