### ISSUE TITLE
Windows Defender: threat detected

### ISSUE THREAD

**Issue by gsf-sellis** [primecoin/primecoin#51]
When I scan primecoin-0.1.3-win32-setup.exe with WIndows Defender it says it is a threat:

Program:Win32/Uwasson.A!ml
Alert Level: Medium
Category: Potentially Unwanted Software
Details: This program has potentially unwanted behavior.

Any one else have this issue? Is it something to worry about?

Is there a checksum I can use to verify the downloaded file from the primecoin.io website?

Thanks

**Comment by gsf-sellis** [comment]
Any of the devs have some insight on this?

**Comment by matt6412** [comment]
its fine, windows pops up warnings all the time for bitcoin related
programs, you can check the source code if you want and build it yourself
if you are concerned

https://github.com/primecoin/primecoin/releases

**Comment by gsf-sellis** [comment]
Hm, ok thanks. I run the bitcoin core wallet and about a half dozen other crypto wallets and none of them give a warning like this. But thanks for the link.

**Comment by sunnyking** [comment]
Primecoin has been popular with cpu mining in 2013. It's possible some virus used it so some antivirus software triggers false alarm on primecoin itself.

**Comment by sunnyking** [comment]
For technical support, please visit our discord server:
https://discord.gg/g9mctgx
