### ISSUE TITLE
Primecoin v1.4.0 32-bit Windows Client won't launch due to compile incompatibility

### ISSUE THREAD

**Issue by mattmill30** [primecoin/primecoin#55]
In an attempt to resolve #54 I have attempted to upgrade to v1.4.0 client, but the Windows 32-bit Primecoin client appears to actually be 64-bit compiled, and so after a successful installation it then fails to launch with the windows error:
![image](https://user-images.githubusercontent.com/6415621/69025729-0cb85800-09c0-11ea-83f0-fc9fd0667130.png)

Given that v1.4.0 is the final version supporting Windows 32-bit, please would you resolve this issue?

**Comment by sunnyking** [comment]
For v0.1.4 only windows 64-bit build is provided. This is explained in the release note. The installation executable has name win32 in it, this might be a source of confusion but the build itself is for 64-bit windows.
